InventoryManagementSystemMe/Controllers/InfoController.cs
using Microsoft.AspNetCore.Mvc;

public class InfoController : Controller
{
    public IActionResult AboutUs()
    {
        return View();
    }

    public IActionResult FAQ()
    {
        return View();
    }
}


InventoryManagementSystemMe/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using InventoryManagementSystemMe.Data;
using InventoryManagementSystemMe.Models;
using System.Collections.Generic;
using System.Threading.Tasks;


namespace InventoryManagementSystemMe.Controllers
{
    [Route("[controller]")]
    public class ProductsController : Controller
    {
        private readonly InventoryManagementContext _context;

        public ProductsController(InventoryManagementContext context)
        {
            _context = context;
        }

        // GET: Products
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var product = await _context.Products.ToListAsync();
            return View(product); // Returns the list view of products
        }

        // GET: Products/Details/5
        [HttpGet("Details/{id}")]
        public async Task<IActionResult> Details(int id)
        {
            var product = await _context.Products.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product); // Returns the details view of a specific products
        }

        // GET: Products/Create
        [HttpGet("Create")]
        public IActionResult Create()
        {
            return View(); // Returns the view for creating a new product
        }

        // POST: Products/Create
        [HttpPost("Create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Product product)
        {
            if (ModelState.IsValid)
            {
                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index)); // Redirects to the product list
            }
            return View(product);
        }

        // GET: Products/Edit/5
        [HttpGet("Edit/{id}")]
        public async Task<IActionResult> Edit(int id)
        {
            var product = await _context.Products.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product); // Returns the edit view for a specific supplier
        }

        // POST: Products/Edit/5
        [HttpPost("Edit/{id}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Product product)
        {
            if (id != product.ProductID)
            {
                return BadRequest();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(id))
                    {
                        return NotFound();
                    }
                    throw;
                }
                return RedirectToAction(nameof(Index)); // Redirects to the product list
            }
            return View(product);
        }

        // GET: Products/Delete/5
        [HttpGet("Delete/{id}")]
        public async Task<IActionResult> Delete(int id)
        {
            var product = await _context.Products.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product); // Returns the delete confirmation view
        }

        // POST: Products/Delete/5
        [HttpPost("Delete/{id}"), ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _context.Products.FindAsync(id);
            if (product != null)
            {
                _context.Products.Remove(product);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index)); // Redirects to the product list
        }

        private bool ProductExists(int id)
        {
            return _context.Products.Any(e => e.ProductID == id);
        }
    }
}

InventoryManagementSystemMe/Controllers/PurchaseController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using InventoryManagementSystemMe.Data;
using InventoryManagementSystemMe.Models;
using System.Collections.Generic;
using System.Threading.Tasks;


namespace InventoryManagementSystemMe.Controllers
{
    [Route("[controller]")]
    public class PurchaseController : Controller
    {
        private readonly InventoryManagementContext _context;

        public PurchaseController(InventoryManagementContext context)
        {
            _context = context;
        }

        // GET: Purchase
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var purchase = await _context.Purchase.ToListAsync();
            return View(purchase); // Returns the list view of purchases
        }

        // GET: Purchase/Details/5
        [HttpGet("Details/{id}")]
        public async Task<IActionResult> Details(int id)
        {
            var purchase = await _context.Products.FindAsync(id);
            if (purchase == null)
            {
                return NotFound();
            }

            return View(purchase); // Returns the details view of a specific purchases
        }

        // GET: Purchases/Create
        [HttpGet("Create")]
        public IActionResult Create()
        {
            return View(); // Returns the view for creating a new purchase
        }

        // POST: Purchase/Create
        [HttpPost("Create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Purchase purchase)
        {
            if (ModelState.IsValid)
            {
                _context.Add(purchase);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index)); // Redirects to the purchase list
            }
            return View(purchase);
        }

        // GET: Purchase/Edit/5
        [HttpGet("Edit/{id}")]
        public async Task<IActionResult> Edit(int id)
        {
            var purchase = await _context.Purchase.FindAsync(id);
            if (purchase == null)
            {
                return NotFound();
            }
            return View(purchase); // Returns the edit view for a specific purchase
        }

        // POST: Purchase/Edit/5
        [HttpPost("Edit/{id}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Purchase purchase)
        {
            if (id != purchase.PurchaseID)
            {
                return BadRequest();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(purchase);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PurchaseExists(id))
                    {
                        return NotFound();
                    }
                    throw;
                }
                return RedirectToAction(nameof(Index)); // Redirects to the purchase list
            }
            return View(purchase);
        }

        // GET: Purchase/Delete/5
        [HttpGet("Delete/{id}")]
        public async Task<IActionResult> Delete(int id)
        {
            var purchase = await _context.Purchase.FindAsync(id);
            if (purchase == null)
            {
                return NotFound();
            }

            return View(purchase); // Returns the delete confirmation view
        }

        // POST: Purchase/Delete/5
        [HttpPost("Delete/{id}"), ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var purchase = await _context.Purchase.FindAsync(id);
            if (purchase != null)
            {
                _context.Purchase.Remove(purchase);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index)); // Redirects to the purchase list
        }

        private bool PurchaseExists(int id)
        {
            return _context.Purchase.Any(e => e.PurchaseID == id);
        }
    }
}

InventoryManagementSystemMe/Controllers/SuppliersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using InventoryManagementSystemMe.Data;
using InventoryManagementSystemMe.Models;
using System.Collections.Generic;
using System.Threading.Tasks;


namespace InventoryManagementSystemMe.Controllers
{
    [Route("[controller]")]
    public class SuppliersController : Controller
    {
        private readonly InventoryManagementContext _context;

        public SuppliersController(InventoryManagementContext context)
        {
            _context = context;
        }

        // GET: Suppliers
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var supplier = await _context.Suppliers.ToListAsync();
            return View(supplier); // Returns the list view of suppliers
        }

        // GET: Suppliers/Details/5
        [HttpGet("Details/{id}")]
        public async Task<IActionResult> Details(int id)
        {
            var supplier = await _context.Suppliers.FindAsync(id);
            if (supplier == null)
            {
                return NotFound();
            }

            return View(supplier); // Returns the details view of a specific supplier
        }

        // GET: Suppliers/Create
        [HttpGet("Create")]
        public IActionResult Create()
        {
            return View(); // Returns the view for creating a new supplier
        }

        // POST: Suppliers/Create
        [HttpPost("Create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Supplier supplier)
        {
            if (ModelState.IsValid)
            {
                _context.Add(supplier);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index)); // Redirects to the supplier list
            }
            return View(supplier);
        }

        // GET: Suppliers/Edit/5
        [HttpGet("Edit/{id}")]
        public async Task<IActionResult> Edit(int id)
        {
            var supplier = await _context.Suppliers.FindAsync(id);
            if (supplier == null)
            {
                return NotFound();
            }
            return View(supplier); // Returns the edit view for a specific supplier
        }

        // POST: Suppliers/Edit/5
        [HttpPost("Edit/{id}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Supplier supplier)
        {
            if (id != supplier.SupplierID)
            {
                return BadRequest();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(supplier);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SupplierExists(id))
                    {
                        return NotFound();
                    }
                    throw;
                }
                return RedirectToAction(nameof(Index)); // Redirects to the supplier list
            }
            return View(supplier);
        }

        // GET: Suppliers/Delete/5
        [HttpGet("Delete/{id}")]
        public async Task<IActionResult> Delete(int id)
        {
            var supplier = await _context.Suppliers.FindAsync(id);
            if (supplier == null)
            {
                return NotFound();
            }

            return View(supplier); // Returns the delete confirmation view
        }

        // POST: Suppliers/Delete/5
        [HttpPost("Delete/{id}"), ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var supplier = await _context.Suppliers.FindAsync(id);
            if (supplier != null)
            {
                _context.Suppliers.Remove(supplier);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index)); // Redirects to the supplier list
        }

        private bool SupplierExists(int id)
        {
            return _context.Suppliers.Any(e => e.SupplierID == id);
        }
    }
}

InventoryManagementSystemMe/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Inventory Management System</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/InventoryManagementSystemMe.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://bootswatch.com/5/minty/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" />
</head>
<body>
    <div class="d-flex">
        <!-- Sidebar -->
        <nav id="sidebar" class="bg-primary text-white p-3 vh-100" style="width: 250px;">
            <h4 class="text-center">
                <a class="text-white text-decoration-none" asp-area="" asp-controller="Home" asp-action="Index">
                    <i class="fa-solid fa-boxes-stacked"></i> Inventory
                </a>
            </h4>
            <ul class="nav flex-column">
                <li class="nav-item">
                    <a class="nav-link text-white" asp-controller="Suppliers" asp-action="Index">
                        <i class="fa-solid fa-truck"></i> Supplier
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" asp-controller="Products" asp-action="Index">
                        <i class="fa-solid fa-box"></i> Product
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" asp-controller="Purchase" asp-action="Index">
                        <i class="fa-solid fa-cart-shopping"></i> Purchase
                    </a>
                </li>
                <hr class="text-white">
                <li class="nav-item">
                    <a class="nav-link text-white" asp-area="" asp-controller="Info" asp-action="AboutUs">
                        <i class="fa-solid fa-info-circle"></i> About Us
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" asp-area="" asp-controller="Info" asp-action="FAQ">
                        <i class="fa-solid fa-question-circle"></i> FAQ
                    </a>
                </li>
            </ul>
        </nav>

        <!-- Main content -->
        <div class="container-fluid">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
    </div>

    <footer class="border-top footer text-muted text-center mt-3">
        <div class="container">
            &copy; 2025 - InventoryManagementSystemMe - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>